#!/bin/bash

cd /dehydrated

./dehydrated --register --accept-terms >> /dev/stdout

if [ -f domains.txt ]; then
  ./dehydrated -c -t dns-01 -k 'hooks/cloudflare/hook.py' >> /dev/stdout
else
  ./dehydrated -c -d $CF_HOST -t dns-01 -k 'hooks/cloudflare/hook.py' >> /dev/stdout
fi
